name:                ChatServer
version:             0.1.0.0
github:              "seckujdivad/ChatServer"
author:              "David Juckes"

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/seckujdivad/ChatServer#readme>

dependencies:
- base >= 4.7 && < 5
- network >= 3.1.1 && < 3.1.2
- bytestring

library:
  source-dirs: src

executables:
  ChatServer-Client:
    main: Client.hs
    source-dirs: app/client
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Client
    dependencies:
    - ChatServer
  ChatServer-Server:
    main: Server.hs
    source-dirs: app/server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Server
    dependencies:
    - ChatServer